# Generated by Django 3.2 on 2022-12-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221221_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='')),
                ('autor', models.CharField(max_length=255)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.articulo')),
            ],
        ),
    ]
